spring:
#  配置数据源
  datasource:
#    配置数据类型
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_plus?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123123

#    自定义mapper的映射文件
#  mapper-locations: classpath*:/mapper/**/*.xml -->默认位置
#  global-config:
#    db-config:
#      table-prefix: t_

#    添加sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  主键的自增类型
  global-config:
    db-config:
      id-type: auto
#      扫描通用枚举

  type-enums-package: com.springboot.mybatisplus.pojo